/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author sarai
 */
public class ASO03 extends javax.swing.JFrame {

    /**
     * Creates new form ASO03
     */
    public ASO03() {
        initComponents();
        setSize(550, 400);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        /*Para que la imagen se adapte a las dimensiones del fondo o jLabel_fondo.*/
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), 
                            jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(iconoFondo);
        /*Para asegurar que la imagen se vea.*/
//        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servicio = new javax.swing.JLabel();
        jLabel_observacion = new javax.swing.JLabel();
        jLabel_elegido = new javax.swing.JLabel();
        jCheckBox_fallas = new javax.swing.JCheckBox();
        jCheckBox_errores = new javax.swing.JCheckBox();
        jCheckBox_accesosNoAutorizados = new javax.swing.JCheckBox();
        jScrollPane_registro = new javax.swing.JScrollPane();
        btnvolver3 = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setText("SERVICIO:");
        getContentPane().add(jLabel_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel_observacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_observacion.setText("OBSERVACIONES:");
        getContentPane().add(jLabel_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel_elegido.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_elegido.setText("Elegido...");
        getContentPane().add(jLabel_elegido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jCheckBox_fallas.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox_fallas.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_fallas.setText("FALLAS (ESTADO)");
        getContentPane().add(jCheckBox_fallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jCheckBox_errores.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox_errores.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_errores.setText("ERRORES DEL SISTEMA");
        getContentPane().add(jCheckBox_errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jCheckBox_accesosNoAutorizados.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox_accesosNoAutorizados.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_accesosNoAutorizados.setText("ACCESOS NO AUTORIZADOS");
        getContentPane().add(jCheckBox_accesosNoAutorizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));
        getContentPane().add(jScrollPane_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 400, 140));

        btnvolver3.setBackground(new java.awt.Color(51, 51, 51));
        btnvolver3.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver3.setText("VOLVER");
        getContentPane().add(btnvolver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnvolver3;
    private javax.swing.JCheckBox jCheckBox_accesosNoAutorizados;
    private javax.swing.JCheckBox jCheckBox_errores;
    private javax.swing.JCheckBox jCheckBox_fallas;
    private javax.swing.JLabel jLabel_elegido;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_observacion;
    private javax.swing.JLabel jLabel_servicio;
    private javax.swing.JScrollPane jScrollPane_registro;
    // End of variables declaration//GEN-END:variables
}
