/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controlador;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.modelo;

/**
 *
 * @author sarai
 */
public class ASO02 extends javax.swing.JFrame {
   
    /**
     * Creates new form ASO02
     */
    public ASO02() {
        
        initComponents();
        setSize(550, 400);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        /*Para que la imagen se adapte a las dimensiones del fondo o jLabel_fondo.*/
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), 
                            jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(iconoFondo);
        /*Para asegurar que la imagen se vea.*/
//        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servicio = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();
        btnincidencias = new javax.swing.JButton();
        btnbasededatos = new javax.swing.JButton();
        lblruta = new javax.swing.JLabel();
        btnfiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servicio.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setText("RUTA:");
        getContentPane().add(jLabel_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        jButton_volver.setBackground(new java.awt.Color(51, 51, 51));
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("VOLVER");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        btnincidencias.setBackground(new java.awt.Color(51, 51, 51));
        btnincidencias.setForeground(new java.awt.Color(255, 255, 255));
        btnincidencias.setText("INCIDENCIAS");
        btnincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincidenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnincidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        btnbasededatos.setBackground(new java.awt.Color(51, 51, 51));
        btnbasededatos.setForeground(new java.awt.Color(255, 255, 255));
        btnbasededatos.setText("GUARDAR BD");
        getContentPane().add(btnbasededatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        lblruta.setBackground(new java.awt.Color(255, 255, 255));
        lblruta.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, 20));

        btnfiltrar.setBackground(new java.awt.Color(51, 51, 51));
        btnfiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnfiltrar.setText("VER/DIRIGIRSE");
        getContentPane().add(btnfiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 170));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
   
    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
   
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void btnincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincidenciasActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabla1;
    public javax.swing.JButton btnbasededatos;
    public javax.swing.JButton btnfiltrar;
    public javax.swing.JButton btnincidencias;
    public javax.swing.JButton jButton_volver;
    public javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_servicio;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblruta;
    // End of variables declaration//GEN-END:variables
}
