/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author sarai
 */
public class ASO03 extends javax.swing.JFrame {

    /**
     * Creates new form ASO03
     */
    public ASO03() {
        initComponents();
        setSize(1180, 560);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        popup();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/images/fondo.jpg"));
        Image imagen = fondo.getImage().getScaledInstance(
        jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_SMOOTH);
        jLabel_fondo.setIcon(new ImageIcon(imagen));
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png"));
        setIconImage(icono);

    }
    
    public void popup(){
        JPopupMenu popumenu=new JPopupMenu();
        JMenuItem item1 =new JMenuItem("Copiar");
        item1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 int[] filas =Tabla1.getSelectedRows(); // varias filas seleccionadas
                int columnas = Tabla1.getColumnCount();

                if (filas.length > 0) {
                StringBuilder sb = new StringBuilder();
    
                for (int fila : filas) {
              for (int col = 0; col < columnas; col++) {
            Object valor = Tabla1.getValueAt(fila, col);
            sb.append(valor).append("\t"); // separador de columnas
             }
            sb.append("\n"); // separador de filas
                 }

    StringSelection seleccion = new StringSelection(sb.toString());
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(seleccion, null);
}   

            }
        });
        popumenu.add(item1);
        Tabla1.setComponentPopupMenu(popumenu);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servicio = new javax.swing.JLabel();
        jLabel_observacion = new javax.swing.JLabel();
        registro = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        btnvolver3 = new javax.swing.JButton();
        fallas = new javax.swing.JButton();
        Errores = new javax.swing.JButton();
        accesos = new javax.swing.JButton();
        lblruta3 = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servicio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setText("Ruta:");
        getContentPane().add(jLabel_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, -1));

        jLabel_observacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_observacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_observacion.setText("Observaciones:");
        getContentPane().add(jLabel_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        registro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        registro.setViewportView(Tabla1);

        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 1080, 250));

        btnvolver3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnvolver3.setText("Volver");
        btnvolver3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(btnvolver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 130, 40));

        fallas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fallas.setText("Fallas");
        getContentPane().add(fallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 110, -1));

        Errores.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Errores.setText("Errores");
        getContentPane().add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 110, -1));

        accesos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        accesos.setText("Accesos no Autorizados");
        accesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesosActionPerformed(evt);
            }
        });
        getContentPane().add(accesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, -1));

        lblruta3.setBackground(new java.awt.Color(255, 255, 255));
        lblruta3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblruta3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblruta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, 30));

        jLabel_fondo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Errores;
    public javax.swing.JTable Tabla1;
    public javax.swing.JButton accesos;
    public javax.swing.JButton btnvolver3;
    public javax.swing.JButton fallas;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_observacion;
    private javax.swing.JLabel jLabel_servicio;
    public javax.swing.JLabel lblruta3;
    public javax.swing.JScrollPane registro;
    // End of variables declaration//GEN-END:variables
}
