/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.sql.*; 
import controlador.controlador;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.*;
import modelo.modelo;
/**
 *
 * @author sarai
 */
public class ASO01 extends javax.swing.JFrame {
    
    /**
     * Creates new form ASO01
     */
    public ASO01() {
        
       
        initComponents();
        setSize(1060, 480);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        /*Para que la imagen se adapte a las dimensiones del fondo o jLabel_fondo.*/
        
       Image imagen = fondo.getImage().getScaledInstance(
            jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_SMOOTH);
        jLabel_fondo.setIcon(new ImageIcon(imagen));

        /*Para asegurar que la imagen se vea.*/
//        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel_servidor = new javax.swing.JLabel();
        jbox1 = new javax.swing.JComboBox<>();
        btnsalir = new javax.swing.JButton();
        btnanalizar = new javax.swing.JButton();
        jLabel_ruta = new javax.swing.JLabel();
        txtruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btningresardatos = new javax.swing.JButton();
        txtmens = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servidor.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_servidor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_servidor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servidor.setText("Servidor:");
        getContentPane().add(jLabel_servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 80, 40));

        jbox1.setBackground(new java.awt.Color(204, 204, 255));
        jbox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbox1.setForeground(new java.awt.Color(0, 0, 0));
        jbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Access", "Error", "FTP" }));
        jbox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 200, 40));

        btnsalir.setBackground(new java.awt.Color(255, 255, 102));
        btnsalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(0, 0, 0));
        btnsalir.setText("Salir");
        btnsalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsalir.setBorderPainted(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 140, 50));

        btnanalizar.setBackground(new java.awt.Color(255, 255, 102));
        btnanalizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnanalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnanalizar.setText("Analizar Logs");
        btnanalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnanalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 160, 50));

        jLabel_ruta.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_ruta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ruta.setText("Ruta:");
        getContentPane().add(jLabel_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 40));

        txtruta.setBackground(new java.awt.Color(255, 255, 102));
        txtruta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtruta.setForeground(new java.awt.Color(0, 0, 0));
        txtruta.setText("Seleccionar ruta del log");
        txtruta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtruta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtruta.setEnabled(false);
        txtruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaActionPerformed(evt);
            }
        });
        getContentPane().add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 370, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btningresardatos.setBackground(new java.awt.Color(255, 255, 102));
        btningresardatos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btningresardatos.setForeground(new java.awt.Color(0, 0, 0));
        btningresardatos.setText("Ingresar Ruta Manualmente");
        btningresardatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btningresardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresardatosActionPerformed(evt);
            }
        });
        getContentPane().add(btningresardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 270, 50));

        txtmens.setBackground(new java.awt.Color(255, 255, 255));
        txtmens.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtmens, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 260, 50));

        jLabel_fondo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void btningresardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresardatosActionPerformed
        
        
    }//GEN-LAST:event_btningresardatosActionPerformed

    private void jbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbox1ActionPerformed
        
    }//GEN-LAST:event_jbox1ActionPerformed

    private void btnanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalizarActionPerformed
               
    }//GEN-LAST:event_btnanalizarActionPerformed
    
    private void txtrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaActionPerformed
        
    }//GEN-LAST:event_txtrutaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        
    }//GEN-LAST:event_btnsalirActionPerformed
    
    
    public String getTxtjbox(){
        return (String)jbox1.getSelectedItem();
    }
    public void setindexjbox(int res){
        jbox1.setSelectedIndex(res);
    }
    public String getTxtruta(){
        return txtruta.getText();
    }
    public void setmensaje(String res){
        txtmens.setText(res);
    }
     public void setruta(String res){
        txtruta.setText(res);
    }
     public void setenabletxtruta(boolean b){
        txtruta.setEnabled(b);
    }
    public void setvisible1(boolean b){
        this.setVisible(b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnanalizar;
    public javax.swing.JButton btningresardatos;
    public javax.swing.JButton btnsalir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_ruta;
    private javax.swing.JLabel jLabel_servidor;
    public javax.swing.JComboBox<String> jbox1;
    public javax.swing.JLabel txtmens;
    public javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
