/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.text.TabableView;
import modelo.modelo;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author sarai
 */
public class ASO02 extends javax.swing.JFrame {
   
    /**
     * Creates new form ASO02
     */
    public ASO02() {
        
        initComponents();
        setSize(1180,560);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        popup();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/images/fondo.jpg"));
        Image imagen = fondo.getImage().getScaledInstance(
        jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_SMOOTH);
        jLabel_fondo.setIcon(new ImageIcon(imagen));
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png"));
        setIconImage(icono);

    }
    public void popup(){
        JPopupMenu popumenu=new JPopupMenu();
        JMenuItem item1 =new JMenuItem("Copiar");
        item1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 int[] filas =Tabla1.getSelectedRows(); // varias filas seleccionadas
                int columnas = Tabla1.getColumnCount();

                if (filas.length > 0) {
                StringBuilder sb = new StringBuilder();
    
                for (int fila : filas) {
              for (int col = 0; col < columnas; col++) {
            Object valor = Tabla1.getValueAt(fila, col);
            sb.append(valor).append("\t"); // separador de columnas
             }
            sb.append("\n"); // separador de filas
                 }

    StringSelection seleccion = new StringSelection(sb.toString());
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(seleccion, null);
}   

            }
        });
        popumenu.add(item1);
        Tabla1.setComponentPopupMenu(popumenu);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servicio = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();
        btnresum = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        btnlistar = new javax.swing.JButton();
        txtfech3 = new com.toedter.calendar.JDateChooser();
        lblruta = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        txtrango = new javax.swing.JButton();
        lblbuscar = new javax.swing.JButton();
        andor = new javax.swing.JTextField();
        combox = new javax.swing.JComboBox<>();
        txtfech = new com.toedter.calendar.JDateChooser();
        txtfech2 = new com.toedter.calendar.JDateChooser();
        txtbuscarfecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnreport1 = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servicio.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setText("RUTA:");
        getContentPane().add(jLabel_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        jButton_volver.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_volver.setText("Volver");
        jButton_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 170, 50));

        btnresum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnresum.setText("Resumen");
        btnresum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnresum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresumActionPerformed(evt);
            }
        });
        getContentPane().add(btnresum, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 140, 50));

        btnactualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 200, 50));

        Tabla1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1080, 280));

        btnlistar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnlistar.setText("Listar");
        btnlistar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 170, 50));

        txtfech3.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtfech3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 150, -1));

        lblruta.setBackground(new java.awt.Color(255, 255, 255));
        lblruta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblruta.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 30));

        txtbuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadoActionPerformed(evt);
            }
        });
        txtbuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscadoKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 220, 30));

        txtrango.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtrango.setText("Buscar Rango");
        txtrango.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, 20));

        lblbuscar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblbuscar.setText("Buscar Ocurrencia");
        lblbuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        getContentPane().add(andor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 220, 30));

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<>", "AND", "OR" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        getContentPane().add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txtfech.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtfech, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 150, -1));

        txtfech2.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtfech2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 150, -1));

        txtbuscarfecha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtbuscarfecha.setText("Buscar Fecha");
        txtbuscarfecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtbuscarfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, -1, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 20, 20));

        btnFiltrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 130, -1));

        btnreport1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnreport1.setText("Reportes");
        btnreport1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreport1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnreport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 170, 50));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
   
    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
   
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void btnresumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresumActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlistarActionPerformed

    private void txtbuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadoActionPerformed

    private void txtbuscadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscadoKeyReleased
       
    }//GEN-LAST:event_txtbuscadoKeyReleased

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnreport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreport1ActionPerformed
     
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabla1;
    public javax.swing.JTextField andor;
    public javax.swing.JButton btnFiltrar;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btnlistar;
    public javax.swing.JButton btnreport1;
    public javax.swing.JButton btnresum;
    public javax.swing.JComboBox<String> combox;
    public javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_servicio;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton lblbuscar;
    public javax.swing.JLabel lblruta;
    public javax.swing.JTextField txtbuscado;
    public javax.swing.JButton txtbuscarfecha;
    public com.toedter.calendar.JDateChooser txtfech;
    public com.toedter.calendar.JDateChooser txtfech2;
    public com.toedter.calendar.JDateChooser txtfech3;
    public javax.swing.JButton txtrango;
    // End of variables declaration//GEN-END:variables
}
