/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author sarai
 */
public class ASO02 extends javax.swing.JFrame {

    /**
     * Creates new form ASO02
     */
    public ASO02() {
        initComponents();
        setSize(550, 400);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        /*Para que la imagen se adapte a las dimensiones del fondo o jLabel_fondo.*/
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), 
                            jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(iconoFondo);
        /*Para asegurar que la imagen se vea.*/
//        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servicio = new javax.swing.JLabel();
        jComboBox_servicio = new javax.swing.JComboBox<>();
        jScrollPane_registro = new javax.swing.JScrollPane();
        jButton_volver = new javax.swing.JButton();
        jButton_incidencias = new javax.swing.JButton();
        jButton_guardarBD = new javax.swing.JButton();
        jButton_ir = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servicio.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servicio.setText("SERVICIO:");
        getContentPane().add(jLabel_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jComboBox_servicio.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));
        getContentPane().add(jScrollPane_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 420, 170));

        jButton_volver.setBackground(new java.awt.Color(51, 51, 51));
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("VOLVER");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jButton_incidencias.setBackground(new java.awt.Color(51, 51, 51));
        jButton_incidencias.setForeground(new java.awt.Color(255, 255, 255));
        jButton_incidencias.setText("INCIDENCIAS");
        getContentPane().add(jButton_incidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jButton_guardarBD.setBackground(new java.awt.Color(51, 51, 51));
        jButton_guardarBD.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardarBD.setText("GUARDAR BD");
        getContentPane().add(jButton_guardarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jButton_ir.setBackground(new java.awt.Color(51, 51, 51));
        jButton_ir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ir.setText("VER/DIRIGIRSE");
        getContentPane().add(jButton_ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardarBD;
    private javax.swing.JButton jButton_incidencias;
    private javax.swing.JButton jButton_ir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JComboBox<String> jComboBox_servicio;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_servicio;
    private javax.swing.JScrollPane jScrollPane_registro;
    // End of variables declaration//GEN-END:variables
}
