/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author sarai
 */
public class ASO01 extends javax.swing.JFrame {

    /**
     * Creates new form ASO01
     */
    public ASO01() {
        initComponents();
        setSize(550, 400);
        /*para que no se pueda modificar el tamaño*/
        setResizable(false);
        setTitle("Analizador de Logs");
        setLocationRelativeTo(null);
        
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        /*Para que la imagen se adapte a las dimensiones del fondo o jLabel_fondo.*/
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), 
                            jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(iconoFondo);
        /*Para asegurar que la imagen se vea.*/
//        this.repaint();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_servidor = new javax.swing.JLabel();
        jComboBox_sevidor = new javax.swing.JComboBox<>();
        jButton_salir = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_analizarLogs = new javax.swing.JButton();
        jLabel_ruta = new javax.swing.JLabel();
        jLabel_mensaje = new javax.swing.JLabel();
        jTextField_ruta = new javax.swing.JTextField();
        jButton_ingresarRutaManualmente = new javax.swing.JButton();
        jLabel_encontrada = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_servidor.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_servidor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_servidor.setText("SERVIDOR:");
        getContentPane().add(jLabel_servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, -1));

        jComboBox_sevidor.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox_sevidor.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_sevidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_sevidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_sevidorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_sevidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jButton_salir.setBackground(new java.awt.Color(51, 51, 51));
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("SALIR");
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jButton_guardar.setBackground(new java.awt.Color(51, 51, 51));
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setText("GUARDAR");
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jButton_analizarLogs.setBackground(new java.awt.Color(51, 51, 51));
        jButton_analizarLogs.setForeground(new java.awt.Color(255, 255, 255));
        jButton_analizarLogs.setText("ANALIZAR LOGS");
        jButton_analizarLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_analizarLogsActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_analizarLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel_ruta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ruta.setText("RUTA:");
        getContentPane().add(jLabel_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel_mensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mensaje.setText("MENSAJE:");
        getContentPane().add(jLabel_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTextField_ruta.setText("rutita...");
        getContentPane().add(jTextField_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, -1));

        jButton_ingresarRutaManualmente.setBackground(new java.awt.Color(51, 51, 51));
        jButton_ingresarRutaManualmente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ingresarRutaManualmente.setText("INGRESAR RUTA MANUALMENTE");
        jButton_ingresarRutaManualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresarRutaManualmenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ingresarRutaManualmente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel_encontrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_encontrada.setText("Respuesta de ruta...");
        getContentPane().add(jLabel_encontrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ingresarRutaManualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresarRutaManualmenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ingresarRutaManualmenteActionPerformed

    private void jComboBox_sevidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_sevidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_sevidorActionPerformed

    private void jButton_analizarLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_analizarLogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_analizarLogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASO01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASO01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_analizarLogs;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_ingresarRutaManualmente;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JComboBox<String> jComboBox_sevidor;
    private javax.swing.JLabel jLabel_encontrada;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_mensaje;
    private javax.swing.JLabel jLabel_ruta;
    private javax.swing.JLabel jLabel_servidor;
    private javax.swing.JTextField jTextField_ruta;
    // End of variables declaration//GEN-END:variables
}
